#!/bin/bash

export $(grep -v '^#' infrastructure.info | xargs)

cat << EOF > production.env
MYSQL_DATABASE=$MYSQL_DATABASE
MYSQL_USERNAME=$MYSQL_USERNAME
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_HOST=$MYSQL_HOST
MYSQL_PORT=$MYSQL_PORT
REDIS_HOST=10.0.1.139
REDIS_DATABASE=$REDIS_DATABASE
REDIS_HOST=$REDIS_HOST
REDIS_PASSWORD=$REDIS_PASSWORD
ELASTIC_ADDRESS=http://127.0.0.1:9200
BANKEND_JOB_ADDRESS=http://$BANKEND_JOB_HOST:8080/xxl-job-admin
WUKONGIM_ADDRESS=http://127.0.0.1:5001
EOF
`


