# 应用 ID，需修改成自己的应用 ID
id: pkg-kc69w3po

# 自定义安装参数，通过 widget 来声明安装表单获取
args:
  - name: app_main_subnet
    label: 主可用区子网
    widget: subnet-select
    regions:
      - "ap-guangzhou"
    description: 主可用区云资源在当前子网下创建

  - name: app_slave_subnet
    label: 备可用区子网
    widget: subnet-select
    regions:
      - "ap-guangzhou"
    description: MySQL、CVM 容灾实例在当前子网下创建
    validator:
      - eq:
          a: ${app_slave_subnet.region}
          b: ${app_main_subnet.region}
          message: 主可用区和备可用区必须一致

  - name: app_clb_sg
    label: CLB 安全组
    widget: security-group-select
    regions:
      - ${app_main_subnet.region}
    validator:
      - eq:
          a: ${app_clb_sg.region}
          b: ${app_main_subnet.region}
          message: 安全组地域与安装网络地域不同

  - name: app_internal_sg
    label: 集群内安全组
    widget: security-group-select
    regions:
      - ${app_main_subnet.region}
    description: 用于集群内云资源，包括 CVM、MySQL 等
    validator:
      - eq:
          a: ${app_internal_sg.region}
          b: ${app_main_subnet.region}
          message: 安全组地域与安装网络地域不同

  - name: cvm_instance_quality
    label: 服务器机型
    widget: cvm-instance-type-select
    region: ${app_main_subnet.region}
    zone: ${app_main_subnet.subnet.zone}
    chargeType: '${charge_type == "PREPAID" ? "PREPAID" : "POSTPAID_BY_HOUR"}'
    cpu: 8
    memory: 16
    incompleteTips: 请先选择安装目标地域

  - name: app_ssl_certificate
    label: 域名 SSL 证书
    widget: certificate-select

  - name: charge_type
    label: 计费类型
    description: 云资源购买使用付费方式
    widget: select
    defaultValue: PREPAID
    options:
      - label: 包年包月
        value: PREPAID
      - label: 按量计费
        value: POSTPAID

  - name: charge_prepaid_period
    label: 购买时长
    widget: input-number
    defaultValue: 1
    description: 云资源包年包月购买的月份数
    when:
      - eq: 
          a: ${charge_type}
          b: "PREPAID" # 包年包月